{
  comptrollers {
    id
    owner
    reserveRateMantissa

    prizePools {
      id
      deactivated
      owner
      trustedForwarder
      comptroller {
        id
      }

      prizePoolType
      compoundPrizePool {
        id
        cToken
      }

      reserveFeeControlledToken

      underlyingCollateralToken
      underlyingCollateralName
      underlyingCollateralSymbol
      underlyingCollateralDecimals

    	maxExitFeeMantissa
      maxTimelockDuration
      timelockTotalSupply
      liquidityCap

      currentPrizeId
      currentState

      cumulativePrizeNet
      cumulativePrizeGross
      cumulativePrizeReserveFee

      prizeStrategy {
        singleRandomWinner {
          id
          owner
          rng
          ticket {
            id
            type
            name
            symbol
            decimals
            totalSupply
          }
          sponsorship {
            id
            type
            name
            symbol
            decimals
            totalSupply
          }

          prizePeriodSeconds
          prizePeriodStartedAt
          prizePeriodEndAt

          externalErc20Awards {
            address
          }
          externalErc721Awards {
            address
            tokenIds
          }
        }
      }

      totalSupply
      totalSponsorship

      playerCount
      players {
        id
        address
        balance
        timelockedBalance
        unlockTimestamp
        cumulativeWinnings
      }

      prizesCount
      prizes {
        id
        awardedBlock
        randomNumber
        amount
        totalTicketSupply
        winners
      }

      tokenCreditRates {
        creditRateMantissa
        creditLimitMantissa
      }

      tokenCreditBalances {
        balance
        timestamp
        initialized
      }

      sponsors {
        id
        address
        balance
      }

      balanceDrips {
        id
        measureToken
        dripToken

        dripRatePerSecond
        exchangeRateMantissa
        timestamp

        players {
          address
        }
      }
      volumeDrips {
        id
        measureToken
        dripToken
        dripAmount

        deactivated
  			referral

        periodSeconds
        periodCount
        periods {
          id
          periodIndex
          totalSupply
          dripAmount
          endTime
          isDripping
        }
        deposits {
          id
          address
          periodIndex
          balance
        }
      }
    }
  }
}
