{
  compoundPrizePoolBuilders {
    id

    comptroller
    trustedForwarder
  }

  prizeStrategies {
    id
    
    creator

    compoundPrizePoolBuilder {
      id
    }
    
    prizePool {
      id
    }

    comptroller
    ticket
    rng
    sponsorship

    currentPrizeId
    currentState

    prizePeriodSeconds
    
    exitFeeMantissa
    creditRateMantissa

    prizes {
      id

      net
      gross
      reserveFee
    }
  }

  prizePools {
    id

    # trustedForwarder
    prizeStrategy

    underlyingCollateralToken
    underlyingCollateralDecimals
    underlyingCollateralName
    underlyingCollateralSymbol

    maxExitFeeMantissa
    maxTimelockDuration
    timelockTotalSupply

    playerCount
    totalSupply
    
    players {
      id
      address
      balance
      timelockedBalance
      unlockTimestamp
    }
  }

  prizes {
    id

    prizeStrategy {
      id
    }
    
    gross
    net
    reserveFee

    randomNumber
    rngRequestId
    
    awardStartOperator
    awardedOperator

    prizePeriodStartedTimestamp
    lockBlock
  
    awardedBlock
    awardedTimestamp

    winners
  }
  
  players {
    id

    address
    balance
    timelockedBalance
    unlockTimestamp
  }
  
  tickets {
    id

    name
    symbol
    decimals
    
    prizeStrategy {
      id
    }
  }
  
  sponsorships {
    id
    
    name
    symbol
    decimals
    
    prizeStrategy {
      id
    }
  }
}