{
  comptrollers {
    id
    owner
    players {
      id
      dripToken
      address
      balance
    }
  }

  prizePools(first:1) {
    id
    deactivated
    owner
    reserve
    trustedForwarder

    prizeStrategy {
      id
      prizePool {
        id
      }
      singleRandomWinner {
        id
        owner
        tokenListener {
          id
        }
        prizePool {
          id
        }
        rng
        ticket {
          id
          totalSupply
        }
        sponsorship {
          id
          totalSupply
        }
        prizePeriodSeconds
        prizePeriodStartedAt
        prizePeriodEndAt
        externalErc20Awards {
          id
        }
        externalErc721Awards {
          id
        }
      }
    }
    prizePoolType
    compoundPrizePool {
      id
      cToken
    }

    reserveFeeControlledToken

    underlyingCollateralToken
    underlyingCollateralName
    underlyingCollateralSymbol
    underlyingCollateralDecimals

    maxExitFeeMantissa
    maxTimelockDuration

    liquidityCap
    timelockTotalSupply

    cumulativePrizeNet
    cumulativePrizeGross
    cumulativePrizeReserveFee

    currentPrize
    currentState

    tokenCreditRates {
      id
    }
    tokenCreditBalances {
      id
    }

    prizesCount
    prizes {
      id
      prizePool {
        id
      }

      awardStartOperator
      awardedOperator
      awardedBlock
      awardedTimestamp

      prizePeriodStartedTimestamp
      lockBlock

      rngRequestId
      randomNumber

      amount
      totalTicketSupply
      winners
    }

    playerCount
    players {
      id
      prizePool {
        id
      }
      address
      balance
      timelockedBalance
      unlockTimestamp
      cumulativeWinnings
    }
    sponsors {
      id
      prizePool {
        id
      }
      address
      balance
    }

    balanceDrips {
      id
      prizePool {
        id
      }
      measureToken
      dripToken
      dripRatePerSecond
      exchangeRateMantissa
      timestamp
      players {
        id
        address
      }
      deactivated
    }
    volumeDrips {
      id
      prizePool {
        id
      }
      measureToken
      dripToken
      referral
      periodSeconds
      periodCount
      dripAmount
      deposits {
        id
        address
        periodIndex
        balance
      }
      periods {
        id
        periodIndex
        totalSupply
        dripAmount
        endTime
        isDripping
      }
      deactivated
    }
  }
}
